name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install "bods-fixtures @ git+https://github.com/StephenAbbott/bods-fixtures.git@v0.1.0"
          pip install --no-deps -e .
          pip install pytest pytest-cov
      - name: Test
        run: pytest -v --cov=pytest_bods_fixtures --cov-report=term-missing
